services:

  database:
    image: postgres:18
    ports:
      - "25432:5432"
    environment:
      POSTGRES_DB: iban_validator_demo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: post1234
    volumes:
      - postgres-data:/var/lib/postgresql

volumes:
  postgres-data:
