version: '3.8'

services:
  app:
    image: iban-validator-demo:latest
    build:
      context: .
    container_name: app
    depends_on:
      - database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/iban_validator_demo
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=post1234
    ports:
      - "8080:8080"

  database:
    image: postgres:18
    container_name: database
    environment:
      POSTGRES_DB: iban_validator_demo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: post1234
    ports:
      - "25432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql

volumes:
  postgres-data:
